version: "3"

services:
  php:
    image: mediaten/php:8.0-fpm
    volumes:
      - ~/.composer-docker/cache:/var/www/.composer/cache
      - ./:/app
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
      - ./docker/php/.bashrc:/var/www/.bashrc
    #      - ~/.ssh:/tmp/.ssh:ro
    environment:
      PHP_USER_ID: 1000
      COMPOSER_MEMORY_LIMIT: -1
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.19.8-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    restart: always
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:laravel.localhost,backend.laravel.localhost"
    networks:
      - default
      - web
    depends_on:
      - php

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:18070:5432
    restart: always

  redis:
    image: redis:6.2.1-alpine
    ports:
      - 127.0.0.1:18060:6379
    restart: always

  node:
    image: node:14.16.0-alpine
    user: "node"
    working_dir: /app
    volumes:
      - ./:/app:delegated
    command: /bin/true

volumes:
  db_data:

networks:
  web:
    external: true
